### ISSUE TITLE
CSS restructuring

### ISSUE THREAD

**Issue by ledevmacedo** [BrazilianBug/Clear-Prod-System#10]
To make the counter replicable. It will be necessary for the CSS to be individual for each situation, thus avoiding conflicts between CSS classes in different projects.

- [x] Add a single CSS file for each counter variant.

- [x] Structure the CSS files that will be shared so that they are just changes and don't conflict with each other. (global resources). 

- [x] Insert According items in the counter (bootstrap)

**Comment by BrazilianBug** [comment]
[Commit solution] https://github.com/BrazilianBug/ClearProdSystem/commit/c41749fa5fb344b854941125022b3da160dbb430
